In [1]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [3]:
# write your code here ^_^
x = np.ones((3,3))

In [4]:
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Q#2: Create y array with elements equal to 0.

In [5]:
# write your code here ^_^
y = np.zeros((3,3))

In [6]:
y

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Q#3: Add x and y arrays.

In [7]:
# write your code here ^_^
x+y

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [9]:
# write your code here ^_^
x.shape

(3, 3)

In [10]:
x.size

9

In [11]:
x.dtype

dtype('float64')

In [12]:
x.ndim

2

In [13]:
x.itemsize

8

In [14]:
x.data

In [15]:
len(x)

3

## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [16]:
# write your code here ^_^
w = np.array([[11,12],[13,14],[15,16]])

In [17]:
w

array([[11, 12],
       [13, 14],
       [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [25]:
# write your code here ^_^
z= np.arange(1, 4).reshape(3,1)

In [26]:
z

array([[1],
       [2],
       [3]])

## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [27]:
# write your code here ^_^

newArray = np.hstack((w,z))

In [28]:
newArray

array([[11, 12,  1],
       [13, 14,  2],
       [15, 16,  3]])

## Q#8: Print all elements of "newArray" using the loop.

In [30]:
# write your code here ^_^
for i in newArray:
    for items in i:
        print(items)

11
12
1
13
14
2
15
16
3


## Q#9: Reverse the columns and rows of "newArray".

In [31]:
# write your code here ^_^
newArray.transpose()

array([[11, 13, 15],
       [12, 14, 16],
       [ 1,  2,  3]])

## Q#10: Decrement all elements of "newArray" with 1.

In [32]:
# write your code here ^_^
newArray -= 1

In [33]:
newArray

array([[10, 11,  0],
       [12, 13,  1],
       [14, 15,  2]])

## Q#11: Find smallest and biggest values in "newArray".

In [35]:
# write your code here ^_^
newArray.min()

0

In [36]:
newArray.max()

15

## Q#12: Print the first row of "newArray" using indexing.

In [37]:
# write your code here ^_^
newArray[0]

array([10, 11,  0])

## Q#13: Print the number equals 12 of "newArray" using indexing.

In [38]:
# write your code here ^_^
newArray[0,2]

12

## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [51]:
# write your code here ^_^
newArray[0,2],newArray[1,1]

(0, 13)

## Q#15: Change the shape of "newArray" to (9,1).

In [52]:
# write your code here ^_^
newArray.reshape(9,1)

array([[10],
       [11],
       [ 0],
       [12],
       [13],
       [ 1],
       [14],
       [15],
       [ 2]])

## Q#16: Change the shape of "newArray" to (3,2).

In [53]:
# write your code here ^_^
newArray.reshape(3,2)

ValueError: cannot reshape array of size 9 into shape (3,2)

# Well Done 🎉